### ISSUE TITLE
Change hello world example to be Bitcoin specific

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#111]
**Is your feature request related to a problem? Please describe.**
The current hello world example is taken from the Solidity guides. This works but doesn't show the capabilities of BOB.

**Describe the solution you'd like**
Change the hello world example to showcase the possibilities of BOB:
- Step 1: Create a smart contract that allows swapping BTC for USDT using the BTC relay
- Step 2: Add account abstraction to the mix so that a user can pay for the EVM-side fees in tBTC/wBTC
- Step 3: Extend the smart contract so that a user can buy an ordinal with USDT.

**Additional context**
See current example: https://docs.gobob.xyz/docs/build/getting-started/helloworld

**Comment by nakul1010** [comment]
@nud3l 
- In steps 1 & step 3 do u want to use `btc_marketplace` and `ord_marketplace` contracts under the hood? So the new `HelloBitcoin` contract will call the above-mentioned contract with the USDT address as a parameter. 
- But this doesn't expose the `BtcRelay` functionality in the `HelloBitcoin` contract directly. 
- OR 
- A new `HelloBitcoin` contract can be created which only uses `BtcRelay` and doesn't have any dependency on the `btc_marketplace` and `ord_marketplace` contracts but will be similar to them.

**Comment by nud3l** [comment]
Create a new `HelloBitcoin` contract that only has a dependency on the relay (your option 2). The idea is for the code to be as instructive and simple as possible and self-contained. 

I think it would be OK to use this repo and put the example in https://github.com/bob-collective/bob/tree/master/src to make sure we keep it up to date with the other code.
