### ISSUE TITLE
Add ordinal support to P2P swap demo

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#114]
**Is your feature request related to a problem? Please describe.**
The current P2P demo doesn't allow to swap ordinals. BOB can do that, so would be great to show it.

**Describe the solution you'd like**

P2P Sell Process

1. Alice (owner of the ordinal) goes to the P2P swap UI and submit a link to the ordinal (ord id) they will sell and a price (in some ERC20). Link current UTXO of ordinal via the ord id in the backend.
2. Alice submits to smart contract: price in ERC20 asset (e.g., 20k USDT), ord id, and UTXO where the ordinal currently lives.
3. Bob (buyer of the ordinal) goes to the P2P swap UI and selects the ordinal to buy.
4. Bob submits to smart contract: lock amount of ERC20 (price) and Bitcoin address and reserve ordinal.
5. Alice goes to P2P UI and sends ordinal to Bob's address using the Leather or Xverse wallet (or other Bitcoin wallet).
6. Alice proofs transfer of the ordinal. Submits to smart contract: SPV proof of the ordinal transfer. Check in the backend that one of the inputs is the original UTXO. Verify that first output is sending to Bob. Alice receives ERC20 tokens (sell price) into her account.

**Open questions**

- Are ordinals always in the first output?

**Context**

- Show ordinals in the P2P table like we do in https://ordinals.gobob.xyz/ - could have the inscription id a link that open the inscription
- Maybe check zkVM demo logic if we have useful code in there

**Comment by gregdhill** [comment]
> Are ordinals always in the first output?

No, they are FIFO ordered (see explanation [here](https://docs.ordinals.com/faq.html#how-does-ordinal-theory-work)), so we need to check the inputs to the transaction to calculate the offset as done [here](https://github.com/ordinals/ord/blob/6115eca37390d8f7c4a37d77522e2edb4a119421/src/subcommand/wallet/transaction_builder.rs#L635) and find which output the sat is spent to. Then we should confirm that the output receiving that Ordinal is spending to Bob.

**Comment by sander2** [comment]
- It's not clear whether one satoshi can contain multiple inscriptions. Technically it can, it just depends on what common indexers accept.
- In the demo, we:
    - Require the seller to provide the UTXO in which the ordinal currently resides
    - only check that that the transaction is spending that transaction, and that it has an output to the buyer's address. We don't check which satoshi is actually transferred, meaning the demo _can_ be cheated.
- In production, we:
    - need to check that the correct satoshi is being spent to the buyer's address. That requires us to know all input amounts. That is not part of the TX structure, so we will need to provide a list of all input transactions in addition to the spv proof of the main tx.
    - In addition to knowing the UTXO that contains the ordinal, we need to know the offset of the ordinal within that UTXO. All new inscriptions are created on offset 0 of their UTXO, but with later transfers, it can end up at different offsets. This offset should be provided together with the UTXO when the sell order is created.
