### ISSUE TITLE
Unify deployed demos into one demo

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#140]
**Is your feature request related to a problem? Please describe.**
We currently have several deployed demos. We should unify these demos into one that showcase the strengths of BOB into a single application instead of having to send users and builders to multiple websites.

**Describe the solution you'd like**

Extend the P2P swap demo to be our one single demo:
- [x] Add BRC20 token support to the demo
- [ ] Add a FAQ sidebar that helps walk people through the demo, similar to Base https://bridge.base.org/deposit
- [ ] Add a CTA to allow users/builders to give us feedback via a Google Form
- [ ] Add the possibility to inscribe testnet ordinals
- [ ] Add the possibility to deploy and mint BRC20
- [ ] Add the option to use our MetaMask snap for both the Bitcoin and the EVM wallet
- [ ] Allow paying for transactions fees using tBTC via Meta Transactions
- [ ] Allow using the P2P demo with smart accounts/account abstraction

The isolated demos should still exist as code examples for builders so that anyone can look at how to implement them without having to comb through a lot of (possibly) unrelated code.

**Context and Alternatives**

I really like demos like https://demo.privy.io/ where you can click around with the different features on one side and then try it out in the other part of the window. Once we have completed the above, we could add a little "customize your demo" sidebar that would allow:

- Activating/deactivation the meta transaction fee payment and add/remove USDT/USDC/wBTC/tBTC as fee payment options
- Activate/deactivate account abstraction with social logins
- Switch between single/dual wallet experience

**Comment by tomjeatt** [comment]
First version of this will be to pull together existing demos with minimal code changes and UI updates. Second version will be a UX-led redesign, using the new BOB branding.

**Comment by nud3l** [comment]
Given that BOB has now been live for a while, we can close this.
