### ISSUE TITLE
Add export for Ordinals Client to the sdk

### ISSUE THREAD

**Issue by danielsimao** [bob-collective/bob#161]
**Is your feature request related to a problem? Please describe.**
Export Ordinals clients in the sdk

**Describe the solution you'd like**
Just add missing export

**Comment by AryanGodara** [comment]
Hi @danielsimao I'd really like to work on this one, to get an idea about the project structure :D
Could you please tell a bit more about what we're aiming to do with this issue

**Comment by gregdhill** [comment]
Already exported
