### ISSUE TITLE
Add broadcast flag to `inscribeData`

### ISSUE THREAD

**Issue by danielsimao** [bob-collective/bob#162]
**Is your feature request related to a problem? Please describe.**
Sometimes is ideal to allow wallet to broadcast transactions instead of doing it in our end. So it is ideal to add this flag and just make `inscribeData` prepare the transaction and return it.

**Describe the solution you'd like**
Add flag that conditionally skips the execution of `broadcast`

**Comment by gregdhill** [comment]
I don't think this is necessary. We are not using this logic in production right now but we can revisit later.
