### ISSUE TITLE
BOB SDK: Alpha launch

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#17]
# Abstract

The BOB SDK is meant as a set of Solidity contracts, Rust and/or TypeScript functions, and UI components to access the unique functions of BOB and make developing new applications on BOB simple.

# Motivation

BOB combines Bitcoin and EVM functionality into a coherent SDK to give anyone access to Bitcoin data, verification functions, account abstraction, and more. The SDK should it make easy for anyone to access to the BOB functionality.

# Specification

## BTC Relay and Libs

- Builders MUST be able to interact with the BTC relay contracts (documentation, Solidity libraries for Bitcoin types, ...)
- Builders MUST be able to verify transaction inclusion with the BTC relay, have an example implementation, and documentation to understand how it works
- Builders MUST be able to verify the inclusion of an ordinal, have an example implementation, and documentation
- Builders MUST be able to verify BRC20 deploy, mint, and transfer operations, have an example implementation, and documentation

## Dev Tooling

- Builders MUST be able to use foundry to develop and deploy contracts on the rollup, see also https://github.com/bluealloy/revm/pull/682
- Builders MUST be able to use remix to develop and deploy contracts on the rollup

## UX Tooling

- Builders MUST be able to allow users paying fees in a bridged BTC deployed as an ERC20. Recommended is to use OpenGSN https://github.com/opengsn/gsn to achieve this with a deployment of OpenGSN for BOB.
- Builders MUST have an easy way to integrate OpenGSN into their contracts

**Comment by danielsimao** [comment]
@nud3l for the task of documenting deploying contracts with remix, should we include verifying and publishing the contract on the chain explorer?

**Comment by nud3l** [comment]
Adding how to verify the contracts would be good to add to the docs in a new subsection after this one: https://docs.gobob.xyz/docs/build/getting-started/helloworld#interact-with-the-coin-contract @danielsimao :
