### ISSUE TITLE
Add Bitcoin transaction creation and signing logic to the SDK

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#247]
**Is your feature request related to a problem? Please describe.**
We are currently implementing Bitcoin signing logic in various places like the SDK and in the sats-wagmi package. The problem is that these implementations diverge and lack testing. I like a single isolate tx creation and signing logic here that we can reuse in node.js scripts, testing suits, or in frontend packages.

**Describe the solution you'd like**

Add the following methods with tests:

*Prio 1*

- [ ] Transfer BTC
- [ ] Transfer BTC with OP_RETURN (needed for onramp)
- [ ] Transfer ordinal with OP_RETURN (needed for ordinals bridge)
- [ ] Transfer Rune with OP_RETURN (needed for runes bridge)

*Prio 2*

- [ ] Inscribe ordinal
- [ ] Inscribe BRC20
- [ ] Etch Rune
- [ ] Transfer ordinal
- [ ] Transfer BRC20
- [ ] Transfer Rune

Build this on https://github.com/paulmillr/scure-btc-signer and https://github.com/paulmillr/micro-ordinals.

Don't use `bitcoinjs-lib`.

**Comment by gregdhill** [comment]
- Transaction creation: BOB SDK
- Signing: [sats-wagmi](https://github.com/bob-collective/sats-wagmi)

We should use `scure-btc-signer` and `bitcoinjs-lib` where it makes sense (something things are impossible to do with the former).
