### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by KyryloKilin** [bob-collective/bob#423]
A broken links on the page: https://docs.gobob.xyz/learn/reference/tools/oracles
![image](https://github.com/user-attachments/assets/fd0f58c6-76d9-4f24-9a84-3fb6a28e7239)

A broken links on the page: https://docs.gobob.xyz/learn/reference/tools/rust-zkvm#running-the-demo
![image](https://github.com/user-attachments/assets/1beb1a22-d4f9-43d1-abb4-0437a144de3a)
![image](https://github.com/user-attachments/assets/75c1390c-cd48-4dbf-97be-bdf67b9d12d8)

**Comment by floor-licker** [comment]
Currently working on this I'll submit a PR in the next couple hours.
