### ISSUE TITLE
Update node info with upcoming Holocene upgrade

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#428]
The Optimism Fork (Holocene) will be activated on ​Mainnet​ on ​`Thu 09 Jan 2025 18:00:01 UTC`

Prior to the update, please confirm the following on external nodes/integrators:
- run op-geth >= [v1.101411.2](https://pylonlinks.com/link?url=https%3A%2F%2Fgithub.com%2Fethereum-optimism%2Fop-geth%2Freleases%2Ftag%2Fv1.101411.2&utm_campaign_id=b0864ff3-1c35-4e96-87fc-2c2706284a23&utm_slack_channel=C081M8AV61K)
- run op-node >= [v1.10.0](https://pylonlinks.com/link?url=https%3A%2F%2Fgithub.com%2Fethereum-optimism%2Foptimism%2Freleases%2Ftag%2Fop-node%252Fv1.10.0&utm_campaign_id=b0864ff3-1c35-4e96-87fc-2c2706284a23&utm_slack_channel=C081M8AV61K)
- set on both the flag  --override.holocene=1736445601

It's the same software version you have updated for your testnet a few weeks ago, the only difference is the timestamp for the fork.

If you are not using the previous fork, Granite, on your external nodes (check the following flags is set ​--override.granite​), please reach out. In the case, you might need to enable the Granite hard fork flags two days before ​Tue 07 Jan 2025 18:00:01 UTC​. You can use the same software version and configure it with ​--override.granite=1736272801

_Originally posted by @nud3l in https://github.com/bob-collective/bob/issues/414#issuecomment-2523407443_

**Comment by derrekcoleman** [comment]
node providers: tenderly, blastAPI
wallets: okx, binance
bridges: layerzero, chainlink, others
app devs: post announcement in Builders TG
