### ISSUE TITLE
BOB: expose testnet and mainet endpoints for bob 

### ISSUE THREAD

**Issue by nakul1010** [bob-collective/bob#51]
**Is your feature request related to a problem? Please describe.**
I propose the addition of paths for both the BOB testnet and mainnet. These paths should be made accessible under the 'gobob' domain. You can find the specific paths by following this link: [Paths Reference](https://github.com/bob-collective/bob/pull/45#discussion_r1364956043). Once this implementation is complete, kindly update the documentation accordingly.

**Additional context**
Originally posted [here](https://github.com/bob-collective/bob/pull/45#discussion_r1364956043)

**Comment by nud3l** [comment]
@nakul1010 could you please update the SDK and docs?

**Comment by nakul1010** [comment]
> @nakul1010 could you please update the SDK and docs?

@nud3l PR #53 will update it.
