### ISSUE TITLE
Gnosis Safe multisig support

### ISSUE THREAD

**Issue by peterslany** [bob-collective/bob#88]
# Add support for Safe (multisig) wallet
![image](https://github.com/bob-collective/bob/assets/47864599/0c77fa3f-923c-42ea-8a34-56ff757ec4d2)
## Findings
Safe wallet https://app.safe.global provides a way to set-up smart contract account with options to create advanced multi-signature wallet.
Currently, Safe multisig wallet supports only selected EVM chains (it does not support any chain like metamask). In order to make them support Bob L2, we would have to reach out to their team.

After the support is added, dApps need to use Safe apps SDK in order to integrate the functionality of app into Gnosis Safe wallet: https://docs.safe.global/safe-apps-sdk/safe-apps

**Comment by nud3l** [comment]
https://safe.gobob.xyz/
